Sort all files at once if not editing in place

diff --git a/bin/bib-order b/bin/bib-order
--- a/bin/bib-order
+++ b/bin/bib-order
@@ -31,6 +31,38 @@ for arg; do
 done
 
 
+# If not check only and not writing in place, sort all
+# bibfiles and possibly stdandard input at once.
+if [ $CHECK -eq 0 ] && [ $INPLACE -eq 0 ]
+then
+    # Iterate bib files.
+    tmp=$(mktemp)
+    for bibfile in "$@"
+    do
+        # Skip options.
+        test "$bibfile" != "-c" || continue
+        test "$bibfile" != "-i" || continue
+        test "$bibfile" != "-r" || continue
+
+        # Skip if not a regular file.
+        test -f "$bibfile" -o "$bibfile" = "-" || {
+            [[ "$bibfile" =~ ^- ]] \
+                && echo "$(basename $0): $bibfile: Unknown option" >/dev/stderr \
+                || echo "$(basename $0): $bibfile: File not found" >/dev/stderr;
+            continue
+        }
+
+        # Append contents to temporary file.
+        cat "$bibfile" >> "$tmp"
+    done
+    # Sort temporary file and print contents.
+    bash $0 -i $OPTIONS "$tmp"
+    cat "$tmp"
+    rm "$tmp"
+    exit 0
+fi
+
+
 # Iterate bib files.
 for bibfile in "$@"
 do
@@ -67,9 +99,5 @@ do
         fi
         # In case of changes override source file.
         diff -q "$tmp" "$bibfile" >/dev/null || mv "$tmp" "$bibfile" || rm "$tmp"
-    else
-        # Print sorted file to stdout.
-        cat "$tmp"
-        rm "$tmp"
     fi
 done
